apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gemma2b
  name: gemma2b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemma2b
  template:
    metadata:
      labels:
        app: gemma2b
    spec:
      containers:
      - name: gemma2b
        image: quay.io/lordofthejars/ollama:0.1.32-gemma2b
        ports:
          - containerPort: 11434
        resources:
          requests: 
            memory: "1000Mi" 
            cpu: "1000m" 
          limits:
            memory: "2000Mi"
            cpu: "2000m"
        readinessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 30
          timeoutSeconds: 2
        startupProbe:
          httpGet:
            path: /api/tags
            port: 11434
          periodSeconds: 10
          failureThreshold: 12
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gemma2b
  labels:
    app: gemma2b    
spec:
  ports:
  - name: http
    port: 11434
  selector:
    app: gemma2b
  type: ClusterIP
