apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog:v1.0.1
        ports:
        - containerPort: 1025
          name: smtp
          protocol: TCP
        - containerPort: 8025
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mailer
  labels:
    app: mailhog
spec:
  ports:
  - name: http
    port: 8025
  - name: smtp
    port: 1025
  selector:
    app: mailhog
  type: LoadBalancer
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: mailhog
  name: mailhog
spec:
  port:
    targetPort: 8025
  tls:
    termination: edge
  to:
    kind: Service
    name: mailer
    weight: 100